# Generated by Django 3.1.7 on 2021-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='point',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=100000000, null=True),
        ),
    ]
