# Generated by Django 3.1.7 on 2021-03-04 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_image',
        ),
    ]
