# Generated by Django 3.1.7 on 2021-03-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210304_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='game',
            name='thumbnail_image',
        ),
        migrations.AddField(
            model_name='game',
            name='sub1_image',
            field=models.ImageField(blank=True, null=True, upload_to='sub1_image/'),
        ),
        migrations.AddField(
            model_name='game',
            name='sub2_image',
            field=models.ImageField(blank=True, null=True, upload_to='sub2_image/'),
        ),
        migrations.AddField(
            model_name='game',
            name='sub3_image',
            field=models.ImageField(blank=True, null=True, upload_to='sub3_image/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='tag',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.game'),
        ),
    ]
