# Generated by Django 3.1.7 on 2021-03-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210313_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author2',
        ),
    ]
