# Generated by Django 3.1.7 on 2021-03-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20210320_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=100000),
        ),
    ]
