# Generated by Django 3.1.7 on 2021-03-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('title',), 'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
    ]
