# Generated by Django 3.1.7 on 2021-03-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20210320_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
