# Generated by Django 3.1.7 on 2021-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0004_auto_20210407_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='geeks_field',
            field=models.CharField(max_length=2),
        ),
    ]
