# Generated by Django 3.1.7 on 2021-04-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0005_auto_20210407_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='geeks_field',
            field=models.BooleanField(),
        ),
    ]
