# Generated by Django 3.1.7 on 2021-04-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0009_auto_20210407_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
