# Generated by Django 3.1.7 on 2021-04-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='active',
        ),
        migrations.AddField(
            model_name='checkout',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='product',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
