# Generated by Django 3.1.7 on 2021-04-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20210327_1934'),
        ('cart', '0009_auto_20210402_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.game'),
            preserve_default=False,
        ),
    ]
