# Generated by Django 3.1.7 on 2021-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_checkout_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='check',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
