# Generated by Django 3.1.7 on 2021-04-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cartitem_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
