# Generated by Django 3.1.7 on 2021-04-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20210402_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='check',
            field=models.BooleanField(default=True),
        ),
    ]
