# Generated by Django 3.1.7 on 2021-04-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20210403_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckOut',
        ),
    ]
