# Generated by Django 3.1.7 on 2021-04-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210330_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameorder',
            options={'ordering': ['-created']},
        ),
    ]
